<template>
  <div class="page capability-page">
    <header class="page-heading">
      <div><span class="eyebrow">{{ kind.toUpperCase() }} REGISTRY</span><h1>{{ kind === 'skill' ? 'Skill 配置' : 'Tool 配置' }}</h1><p>{{ kind === 'skill' ? '编辑 Skill 描述与激活版本，供 Agent 绑定使用。' : '编辑工具适配器、权限和执行策略，供 Agent 安全调用。' }}</p></div>
      <div class="heading-actions"><button class="secondary-button" type="button" @click="runUnitTest">单元测试</button><button class="secondary-button" type="button" :disabled="loading" @click="load">{{ loading ? '刷新中…' : '刷新目录' }}</button><button class="primary-button" type="button" @click="newEntry">＋ 新建{{ kind === 'skill' ? ' Skill' : ' Capability' }}</button></div>
    </header>
    <div v-if="error" class="notice error-notice">{{ error }}</div>
    <div v-if="unitTest" class="notice" :class="unitTest.ok ? 'test-success' : 'error-notice'"><strong>{{ unitTest.ok ? '✓ 配置单元测试通过' : '× 配置单元测试未通过' }}</strong><span v-for="item in unitTest.checks" :key="item" class="test-check">{{ item }}</span></div>
    <div class="capability-workspace">
      <aside class="panel capability-directory"><div class="directory-heading"><div><span class="eyebrow">PUBLISHED CATALOG</span><strong>{{ entries.length }} 个{{ kind === 'skill' ? ' Skill' : ' Capability' }}</strong></div><input v-model.trim="search" type="search" placeholder="搜索名称或 ID" /></div><button v-for="entry in filteredEntries" :key="entry.ref.capability_id" class="catalog-entry" :class="{ active: selectedId === entry.ref.capability_id }" type="button" @click="select(entry)"><span class="catalog-mark">{{ kind === 'skill' ? 'S' : 'C' }}</span><span><strong>{{ entry.name }}</strong><small>{{ entry.ref.capability_id }} · v{{ entry.ref.version }}</small></span></button><div v-if="!filteredEntries.length" class="empty-state compact"><span>◇</span><strong>暂无{{ kind === 'skill' ? ' Skill' : ' Capability' }}</strong></div></aside>
      <main class="panel capability-editor"><div class="editor-header"><div><span class="eyebrow">IMMUTABLE VERSION</span><h2>{{ form.name || `新建${kind === 'skill' ? ' Skill' : ' Capability'}` }}</h2><p v-if="form.id"><code>{{ form.id }} · {{ form.version }}</code></p></div><div class="editor-actions"><button class="secondary-button" type="button" @click="newEntry">重置</button><button class="primary-button" type="button" :disabled="saving || !canSave" @click="save">{{ saving ? '发布中…' : '发布新版本' }}</button></div></div>
        <form class="editor-form" @submit.prevent="save"><div class="form-grid"><label><span>{{ kind === 'skill' ? 'Skill' : 'Capability' }} ID</span><input v-model.trim="form.id" required placeholder="research.capability" /></label><label><span>版本</span><input v-model.trim="form.version" required placeholder="1.0.0" /></label><label><span>名称</span><input v-model.trim="form.name" required /></label><label><span>Adapter</span><input v-model.trim="form.adapter" required :placeholder="kind === 'skill' ? 'prompt-skill:research' : 'native:web_search'" /></label><label class="wide"><span>描述</span><textarea v-model="form.description" rows="4" /></label><label><span>执行模式</span><select v-model="form.execution_mode"><option value="immediate">立即执行</option><option value="queued">队列执行</option><option value="streaming">流式执行</option></select></label><label><span>副作用</span><select v-model="form.side_effect"><option value="none">无</option><option value="read">只读</option><option value="write">写入</option><option value="external">外部副作用</option></select></label><label><span>超时（秒）</span><input v-model.number="form.timeout_seconds" type="number" min="1" /></label><label><span>预期耗时（秒）</span><input v-model.number="form.expected_duration_seconds" type="number" min="0" /></label><label class="wide"><span>Tags（逗号分隔）</span><input v-model.trim="form.tags" placeholder="research, web, safe" /></label><label class="wide"><span>所需权限（逗号分隔）</span><input v-model.trim="form.permissions" placeholder="network.read, filesystem.read" /></label><label class="wide"><span>Input Schema（JSON）</span><textarea v-model="form.input_schema" rows="6" spellcheck="false" /></label><label class="wide"><span>Output Schema（JSON）</span><textarea v-model="form.output_schema" rows="6" spellcheck="false" /></label></div></form>
        <div class="release-options"><label><span>发布生效</span><select v-model="releasePolicy.activation_mode"><option value="automatic">预热后自动生效</option><option value="manual">预热后等待批准</option></select></label><label><span>预热超时（秒）</span><input v-model.number="releasePolicy.timeout_seconds" type="number" min="10" max="86400" /></label><label class="release-check"><input v-model="releasePolicy.require_healthy_workers" type="checkbox" />必须存在健康 Worker</label><label class="release-check"><input v-model="releasePolicy.auto_rollback" type="checkbox" />失败保护旧版本</label></div>
        <div v-if="selectedId" class="notice version-note">已发布版本不可修改；编辑后请使用新的版本号重新发布。Agent 绑定的 Skill 版本也会保持不变。</div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { getAdminCapabilities, publishCapability, type AdminCapability } from '../api/admin'

const route = useRoute()
const kind = computed(() => route.path.includes('/skills') ? 'skill' : 'tool')
const entries = ref<AdminCapability[]>([]); const selectedId = ref(''); const search = ref(''); const loading = ref(false); const saving = ref(false); const error = ref(''); const unitTest = ref<{ ok: boolean; checks: string[] } | null>(null)
const blank = () => ({ id: '', version: '1.0.0', name: '', adapter: '', description: '', execution_mode: 'immediate', side_effect: 'none', timeout_seconds: 60, expected_duration_seconds: 10, tags: '', permissions: '', input_schema: '{\n  "type": "object"\n}', output_schema: '{\n  "type": "object"\n}' })
const form = reactive(blank())
const releasePolicy = reactive({ activation_mode: 'automatic' as 'automatic' | 'manual', timeout_seconds: 300, auto_rollback: true, require_healthy_workers: true })
const filteredEntries = computed(() => { const term = search.value.toLowerCase(); return entries.value.filter((entry) => !term || `${entry.name} ${entry.ref.capability_id}`.toLowerCase().includes(term)) })
const canSave = computed(() => Boolean(form.id && form.version && form.name && form.adapter))
function list(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean) }
function parseSchema(value: string) { try { const parsed = JSON.parse(value); if (!parsed || parsed.type !== 'object') throw new Error('Schema 顶层 type 必须为 object'); return parsed } catch (e) { throw new Error(e instanceof Error ? `Schema JSON 无效：${e.message}` : 'Schema JSON 无效') } }
function runUnitTest() { const checks: string[] = []; let ok = true; if (!form.id || !form.version || !form.name || !form.adapter) { checks.push('ID、版本、名称和 Adapter 必填'); ok = false } else checks.push('基础字段完整'); try { parseSchema(form.input_schema); checks.push('Input Schema JSON 有效') } catch (e) { checks.push(e instanceof Error ? e.message : 'Input Schema 无效'); ok = false } try { parseSchema(form.output_schema); checks.push('Output Schema JSON 有效') } catch (e) { checks.push(e instanceof Error ? e.message : 'Output Schema 无效'); ok = false } if (form.timeout_seconds <= 0) { checks.push('超时时间必须大于 0'); ok = false } else checks.push('执行参数有效'); unitTest.value = { ok, checks } }
function newEntry() { selectedId.value = ''; Object.assign(form, blank()) }
function select(entry: AdminCapability) { selectedId.value = entry.ref.capability_id; Object.assign(form, { ...blank(), id: entry.ref.capability_id, version: entry.ref.version, name: entry.name, adapter: entry.adapter, description: entry.description, tags: entry.tags.join(', '), permissions: entry.permissions.join(', ') }) }
async function load() { loading.value = true; error.value = ''; try { entries.value = (await getAdminCapabilities()).filter((entry) => entry.ref.kind === kind.value); if (!selectedId.value && entries.value.length) select(entries.value[0]) } catch (e) { error.value = e instanceof Error ? e.message : '读取能力目录失败' } finally { loading.value = false } }
async function save() { if (!canSave.value) return; saving.value = true; error.value = ''; try { await publishCapability(form.id, form.version, { kind: kind.value, name: form.name, description: form.description, adapter: form.adapter, tags: list(form.tags), permissions: list(form.permissions), execution_mode: form.execution_mode, side_effect: form.side_effect, timeout_seconds: form.timeout_seconds, expected_duration_seconds: form.expected_duration_seconds, input_schema: parseSchema(form.input_schema), output_schema: parseSchema(form.output_schema), idempotent: true, retryable: true, supports_stream: form.execution_mode === 'streaming', rollout_policy: releasePolicy }); await load(); select(entries.value.find((entry) => entry.ref.capability_id === form.id) || entries.value[0]); error.value = ''; } catch (e) { error.value = e instanceof Error ? e.message : '发布失败' } finally { saving.value = false } }
watch(kind, () => { newEntry(); void load() }, { immediate: true })
</script>

<style scoped>
.capability-workspace { display: grid; grid-template-columns: 300px minmax(0,1fr); gap: 16px; align-items: start; }.capability-directory { overflow: hidden; }.directory-heading { display: grid; gap: 14px; padding: 20px 16px 15px; }.directory-heading>div { display: flex; justify-content: space-between; align-items: center; }.directory-heading strong { color: var(--text-strong); font-size: 12px; }.directory-heading input { width: 100%; padding: 9px 10px; color: var(--text); background: var(--input); border: 1px solid var(--border); border-radius: 9px; }.catalog-entry { display: grid; width: 100%; grid-template-columns: 30px minmax(0,1fr); gap: 10px; align-items: center; padding: 13px 16px; text-align: left; color: var(--text); background: transparent; border: 0; border-top: 1px solid var(--border); cursor: pointer; }.catalog-entry:hover,.catalog-entry.active { background: var(--accent-subtle); }.catalog-entry>span:last-child { display: grid; gap: 3px; min-width: 0; }.catalog-entry strong,.catalog-entry small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.catalog-entry strong { color: var(--text-strong); font-size: 12px; }.catalog-entry small { color: var(--text-muted); font: 9px var(--font-mono); }.catalog-mark { display: grid; width: 30px; height: 30px; place-items: center; color: var(--accent); background: var(--accent-subtle); border-radius: 8px; font-weight: 700; }.capability-editor { min-width: 0; overflow: hidden; }.editor-header { display: flex; justify-content: space-between; align-items: center; gap: 16px; padding: 20px 22px; }.editor-header h2 { margin: 5px 0 2px; color: var(--text-strong); font-size: 19px; }.editor-header p { margin: 0; color: var(--text-muted); font-size: 10px; }.editor-actions { display: flex; gap: 8px; }.editor-form { border-top: 1px solid var(--border); }.form-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 15px; padding: 20px 22px; }.form-grid label { display: grid; gap: 6px; color: var(--text-muted); font-size: 10px; }.form-grid label.wide { grid-column: 1/-1; }.form-grid input,.form-grid select,.form-grid textarea { width: 100%; padding: 9px 10px; color: var(--text); background: var(--input); border: 1px solid var(--border-strong); border-radius: 9px; outline: none; }.form-grid textarea { resize: vertical; font-family: var(--font-mono); line-height: 1.6; }.version-note { margin: 0 22px 22px; color: var(--text-muted); background: var(--surface-raised); border: 1px solid var(--border); }.error-notice { white-space: pre-wrap; }.error-notice:empty { display: none; }
.test-success { color: var(--success); background: rgba(50,182,122,.08); border: 1px solid rgba(50,182,122,.22); }.test-check { display: block; margin-top: 3px; color: var(--text-muted); font-size: 11px; }
.release-options { display:grid;grid-template-columns:minmax(200px,1fr) 150px auto auto;gap:12px;align-items:end;margin:0 22px 18px;padding:14px;background:var(--surface-raised);border:1px solid var(--border);border-radius:10px }.release-options label { display:grid;gap:6px;color:var(--text-muted);font-size:10px }.release-options input,.release-options select { width:100%;padding:9px 10px;color:var(--text);background:var(--input);border:1px solid var(--border-strong);border-radius:9px }.release-options .release-check { display:flex;align-items:center;gap:7px;padding-bottom:10px;white-space:nowrap }.release-options .release-check input { width:auto }
@media (max-width: 850px) { .capability-workspace { grid-template-columns: 1fr; }.catalog-entry { display: flex; width: auto; min-width: 220px; border: 1px solid var(--border); border-radius: 9px; }.capability-directory { display: flex; flex-wrap: wrap; gap: 8px; padding: 12px; }.directory-heading { width: 100%; padding: 4px; }.catalog-entry+.catalog-entry { border-top: 1px solid var(--border); } }
@media (max-width: 600px) { .editor-header { align-items: flex-start; flex-direction: column; }.form-grid { grid-template-columns: 1fr; padding: 16px; }.form-grid label.wide { grid-column: auto; }.version-note { margin: 0 16px 16px; } }
</style>
