<template>
  <div class="page mcp-page">
    <header class="page-heading"><div><span class="eyebrow">MODEL CONTEXT PROTOCOL</span><h1>外部 MCP Server</h1><p>直接接入外部 MCP 工具服务，支持 Streamable HTTP 与本地 stdio。</p></div><div class="heading-actions"><button class="secondary-button" type="button" @click="importOfficialExample">导入官方示例</button><button class="secondary-button" type="button" :disabled="loading" @click="load">{{ loading ? '刷新中…' : '刷新列表' }}</button><button class="primary-button" type="button" @click="newServer">＋ 添加 MCP Server</button></div></header>
    <div v-if="error" class="notice error-notice">{{ error }}</div><div v-if="notice" class="notice" :class="notice.ok ? 'test-success' : 'error-notice'"><strong>{{ notice.ok ? '✓' : '×' }} {{ notice.message }}</strong></div>
    <div class="mcp-workspace"><aside class="panel server-list"><div class="panel-heading"><div><span class="eyebrow">CONNECTIONS</span><h2>{{ servers.length }} 个服务</h2></div></div><button v-for="server in servers" :key="server.name" class="server-row" :class="{ active: selectedName === server.name }" type="button" @click="select(server)"><span class="server-dot" :class="{ disabled: !server.enabled }"/><span><strong>{{ server.name }}</strong><small>{{ server.url || `${server.command} ${server.args.join(' ')}` }}</small></span></button><div v-if="!servers.length" class="empty-state compact"><span>◇</span><strong>尚未配置 MCP</strong></div></aside>
      <main class="panel mcp-editor"><div class="panel-heading"><div><span class="eyebrow">SERVER CONFIGURATION</span><h2>{{ form.name || '新建 MCP Server' }}</h2><p class="panel-desc">保存后由 Worker 在下次启动/重载时建立连接。</p></div><div class="editor-actions"><button v-if="selectedName" class="danger-button" type="button" @click="remove">删除</button><button class="secondary-button" type="button" @click="test" :disabled="!selectedName || testing">{{ testing ? '测试中…' : '连接测试' }}</button><button class="primary-button" type="button" @click="save" :disabled="saving || !canSave">{{ saving ? '保存中…' : '保存配置' }}</button></div></div>
        <form class="mcp-form" @submit.prevent="save"><label><span>Server Name</span><input v-model.trim="form.name" required pattern="[A-Za-z0-9_-]+" placeholder="github-mcp" /></label><label class="switch-label"><input v-model="form.enabled" type="checkbox" /><span><strong>启用此服务</strong><small>禁用后 Worker 不会连接</small></span></label><div class="transport-toggle"><button type="button" :class="{ active: transport === 'http' }" @click="transport = 'http'">Streamable HTTP</button><button type="button" :class="{ active: transport === 'stdio' }" @click="transport = 'stdio'">本地 stdio</button></div><label v-if="transport === 'http'" class="wide"><span>Endpoint URL</span><input v-model.trim="form.url" type="url" required placeholder="https://mcp.example.com/mcp" /><small class="field-hint">服务端会执行 DNS / SSRF 安全校验。</small></label><template v-else><label><span>Command</span><input v-model.trim="form.command" required placeholder="npx" /></label><label><span>Arguments（每行一个）</span><textarea v-model="form.args" rows="4" placeholder="-y\n@modelcontextprotocol/server-filesystem\n/workspace" /></label></template><label class="wide"><span>Environment Variables（JSON）</span><textarea v-model="form.env" rows="5" spellcheck="false" placeholder='{ "GITHUB_TOKEN": "…" }' /><small class="field-hint">已保存的环境变量值不会回显；编辑已有服务时请谨慎覆盖。</small></label></form>
      </main>
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useMessage } from 'naive-ui'
import { deleteMCPServer, getMCPServers, saveMCPServer, testMCPServer, type MCPServerConfig } from '../api/admin'
const message = useMessage(); const servers = ref<MCPServerConfig[]>([]); const selectedName = ref(''); const loading = ref(false); const saving = ref(false); const testing = ref(false); const error = ref(''); const notice = ref<{ ok: boolean; message: string } | null>(null); const transport = ref<'http' | 'stdio'>('http')
const blank = () => ({ name: '', enabled: true, command: '', args: '', url: '', env: '{}' }); const form = reactive(blank()); const canSave = computed(() => Boolean(form.name && (transport.value === 'http' ? form.url : form.command)))
function newServer() { selectedName.value = ''; Object.assign(form, blank()); transport.value = 'http'; notice.value = null }
function importOfficialExample() { selectedName.value = ''; Object.assign(form, { ...blank(), name: 'filesystem', command: 'npx', args: '-y\n@modelcontextprotocol/server-filesystem\n/workspace' }); transport.value = 'stdio'; notice.value = { ok: true, message: '已导入官方 Filesystem MCP 示例，请确认允许访问的目录后保存' } }
function select(server: MCPServerConfig) { selectedName.value = server.name; Object.assign(form, { ...blank(), name: server.name, enabled: server.enabled, command: server.command, args: server.args.join('\n'), url: server.url }); transport.value = server.url ? 'http' : 'stdio'; notice.value = null }
async function load() { loading.value = true; error.value = ''; try { servers.value = await getMCPServers(); if (!selectedName.value && servers.value.length) select(servers.value[0]) } catch (e) { error.value = e instanceof Error ? e.message : '读取 MCP 配置失败' } finally { loading.value = false } }
function envValue() { try { const value = JSON.parse(form.env || '{}'); if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error('Environment 必须是 JSON 对象'); return value as Record<string, string> } catch (e) { throw new Error(e instanceof Error ? e.message : 'Environment JSON 无效') } }
async function save() { if (!canSave.value) return; saving.value = true; error.value = ''; try { await saveMCPServer(form.name, { enabled: form.enabled, command: transport.value === 'stdio' ? form.command : '', args: transport.value === 'stdio' ? form.args.split('\n').map((v) => v.trim()).filter(Boolean) : [], env: envValue(), url: transport.value === 'http' ? form.url : '' }); selectedName.value = form.name; await load(); notice.value = { ok: true, message: 'MCP 配置已保存' } } catch (e) { error.value = e instanceof Error ? e.message : '保存 MCP 配置失败' } finally { saving.value = false } }
async function test() { if (!selectedName.value) return; testing.value = true; try { const result = await testMCPServer(selectedName.value); notice.value = result } catch (e) { notice.value = { ok: false, message: e instanceof Error ? e.message : 'MCP 连接测试失败' } } finally { testing.value = false } }
async function remove() { if (!selectedName.value) return; try { await deleteMCPServer(selectedName.value); message.success('MCP Server 已删除'); newServer(); await load() } catch (e) { error.value = e instanceof Error ? e.message : '删除失败' } }
onMounted(load)
</script>
<style scoped>
.mcp-workspace { display: grid; grid-template-columns: 300px minmax(0,1fr); gap: 16px; align-items: start; }.server-list { overflow: hidden; }.server-row { display: grid; width: 100%; grid-template-columns: 10px minmax(0,1fr); gap: 10px; padding: 14px 18px; text-align: left; color: var(--text); background: transparent; border: 0; border-top: 1px solid var(--border); cursor: pointer; }.server-row:hover,.server-row.active { background: var(--accent-subtle); }.server-row>span:last-child { display: grid; gap: 3px; min-width: 0; }.server-row strong,.server-row small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.server-row strong { color: var(--text-strong); font-size: 12px; }.server-row small { color: var(--text-muted); font: 9px var(--font-mono); }.server-dot { width: 8px; height: 8px; margin-top: 4px; border-radius: 50%; background: var(--success); }.server-dot.disabled { background: var(--text-muted); }.mcp-editor { overflow: hidden; }.panel-heading { align-items: flex-start; }.panel-desc { margin: 5px 0 0; color: var(--text-muted); font-size: 10px; }.editor-actions { display: flex; gap: 8px; }.mcp-form { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 16px; padding: 22px; border-top: 1px solid var(--border); }.mcp-form label { display: grid; gap: 6px; color: var(--text-muted); font-size: 10px; }.mcp-form .wide { grid-column: 1/-1; }.mcp-form input,.mcp-form textarea { width: 100%; padding: 10px; color: var(--text); background: var(--input); border: 1px solid var(--border-strong); border-radius: 9px; outline: none; }.mcp-form textarea { resize: vertical; font-family: var(--font-mono); line-height: 1.55; }.switch-label { display: flex !important; grid-template-columns: auto 1fr; align-items: center; gap: 10px !important; padding: 10px; background: var(--surface-raised); border: 1px solid var(--border); border-radius: 9px; }.switch-label input { width: auto; }.switch-label span { display: grid; gap: 2px; }.switch-label strong { color: var(--text); font-size: 11px; }.field-hint { color: var(--text-muted); font-size: 9px; }.transport-toggle { display: flex; grid-column: 1/-1; gap: 7px; }.transport-toggle button { padding: 9px 12px; color: var(--text-muted); background: var(--surface-raised); border: 1px solid var(--border); border-radius: 8px; cursor: pointer; }.transport-toggle button.active { color: var(--text-strong); background: var(--accent-subtle); border-color: var(--accent-border); }.test-success { color: var(--success); background: rgba(50,182,122,.08); border: 1px solid rgba(50,182,122,.22); }
@media (max-width: 850px) { .mcp-workspace { grid-template-columns: 1fr; }.mcp-form { grid-template-columns: 1fr; }.mcp-form .wide,.transport-toggle { grid-column: auto; } }.error-notice:empty { display: none; }
</style>
