"""Plugin hooks module - lifecycle hooks for agent, tools, messages, etc."""

from joyhousebot.plugins.hooks.types import (
    HookName,
    HookContext,
    BeforeAgentStartEvent,
    BeforeAgentStartResult,
    AgentEndEvent,
    BeforeCompactionEvent,
    AfterCompactionEvent,
    BeforeResetEvent,
    MessageReceivedEvent,
    MessageSendingEvent,
    MessageSendingResult,
    MessageSentEvent,
    BeforeToolCallEvent,
    BeforeToolCallResult,
    AfterToolCallEvent,
    ToolResultPersistEvent,
    ToolResultPersistResult,
    SessionStartEvent,
    SessionEndEvent,
    GatewayStartEvent,
    GatewayStopEvent,
    HookHandler,
    PluginHookRegistration,
)
from joyhousebot.plugins.hooks.dispatcher import (
    HookDispatcher,
    get_hook_dispatcher,
    reset_hook_dispatcher,
    emit_hook,
    emit_hook_first_result,
)

__all__ = [
    "HookName",
    "HookContext",
    "BeforeAgentStartEvent",
    "BeforeAgentStartResult",
    "AgentEndEvent",
    "BeforeCompactionEvent",
    "AfterCompactionEvent",
    "BeforeResetEvent",
    "MessageReceivedEvent",
    "MessageSendingEvent",
    "MessageSendingResult",
    "MessageSentEvent",
    "BeforeToolCallEvent",
    "BeforeToolCallResult",
    "AfterToolCallEvent",
    "ToolResultPersistEvent",
    "ToolResultPersistResult",
    "SessionStartEvent",
    "SessionEndEvent",
    "GatewayStartEvent",
    "GatewayStopEvent",
    "HookHandler",
    "PluginHookRegistration",
    "HookDispatcher",
    "get_hook_dispatcher",
    "reset_hook_dispatcher",
    "emit_hook",
    "emit_hook_first_result",
]
