/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmbeddingProfiles: typeof import('./src/components/EmbeddingProfiles.vue')['default']
    ExecutionTimeline: typeof import('./src/components/ExecutionTimeline.vue')['default']
    ImpersonationControl: typeof import('./src/components/ImpersonationControl.vue')['default']
    MarkdownContent: typeof import('./src/components/MarkdownContent.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaConfigurationForm: typeof import('./src/components/SchemaConfigurationForm.vue')['default']
    ShellLayout: typeof import('./src/components/ShellLayout.vue')['default']
  }
}
