"""Narrow structural storage ports for the durable Runtime execution core."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, cast

from porthouse.contracts.events import AgentEvent
from porthouse.domain.agents import AgentExecutionSnapshot, AgentRevision


class RunStorePort(Protocol):
    def create_runtime_run(self, **kwargs: Any) -> tuple[Any, bool]: ...

    def get_runtime_run(self, run_id: str, expected_user_id: str | None = None) -> Any: ...

    def claim_runtime_run(self, run_id: str, **kwargs: Any) -> Any: ...

    def heartbeat_runtime_run(self, run_id: str, **kwargs: Any) -> bool: ...

    def list_incomplete_runtime_runs(self, limit: int = 500) -> list[Any]: ...

    def update_runtime_run(self, run_id: str, **kwargs: Any) -> bool: ...

    def request_runtime_cancel(self, run_id: str, **kwargs: Any) -> dict[str, Any] | None: ...

    def finish_runtime_run_bundle(
        self, run_id: str, **kwargs: Any
    ) -> tuple[list[AgentEvent], AgentEvent] | None: ...

    def reset_runtime_run(self, run_id: str) -> bool: ...

    def suspend_run_for_approval(self, **kwargs: Any) -> bool: ...

    def suspend_run_for_reconciliation(self, **kwargs: Any) -> bool: ...

    def list_runtime_runs(self, **kwargs: Any) -> list[Any]: ...


class TaskStorePort(Protocol):
    def create_runtime_task(self, **kwargs: Any) -> Any: ...

    def get_runtime_task(self, task_id: str) -> Any: ...

    def list_runtime_tasks(self, run_id: str, *, limit: int = 1000) -> list[Any]: ...

    def claim_runtime_task(self, **kwargs: Any) -> Any: ...

    def update_runtime_task(self, task_id: str, **kwargs: Any) -> bool: ...

    def cancel_runtime_tasks(self, run_id: str, **kwargs: Any) -> int: ...

    def has_claimable_runtime_task(self) -> bool: ...

    def has_incomplete_runtime_work(self) -> bool: ...

    def heartbeat_runtime_task(self, task_id: str, **kwargs: Any) -> bool: ...

    def get_runtime_task_dependencies(self, task_id: str) -> list[str]: ...


class EventStorePort(Protocol):
    def get_runtime_run(self, run_id: str, expected_user_id: str | None = None) -> Any: ...

    def append_runtime_event(self, event: AgentEvent) -> AgentEvent: ...

    def list_runtime_events(
        self,
        run_id: str,
        *,
        after_sequence: int = 0,
        limit: int = 1000,
    ) -> list[AgentEvent]: ...


class GraphStorePort(Protocol):
    def create_runtime_graph(self, **kwargs: Any) -> Any: ...

    def materialize_runtime_graph(self, **kwargs: Any) -> Any: ...

    def start_runtime_graph(self, run_id: str, **kwargs: Any) -> bool: ...

    def reconcile_runtime_graph(self, run_id: str, **kwargs: Any) -> Any: ...

    def reset_runtime_graph(self, run_id: str) -> bool: ...

    def suspend_graph_task_for_approval(self, task_id: str, **kwargs: Any) -> bool: ...

    def suspend_graph_task_for_reconciliation(self, task_id: str, **kwargs: Any) -> bool: ...

    def expire_due_graph_event_waits(self, **kwargs: Any) -> list[Any]: ...

    def get_runtime_saga(self, run_id: str) -> dict[str, Any] | None: ...

    def reconcile_runtime_saga(self, run_id: str) -> dict[str, Any] | None: ...

    def trigger_runtime_saga(self, run_id: str) -> Any: ...

    def suspend_graph_task_for_explicit_approval(self, **kwargs: Any) -> Any: ...

    def suspend_graph_task_for_event(self, **kwargs: Any) -> Any: ...

    def suspend_graph_task_for_subrun(self, **kwargs: Any) -> bool: ...

    def complete_runtime_branch(self, **kwargs: Any) -> bool: ...

    def expand_runtime_foreach(self, **kwargs: Any) -> Any: ...

    def complete_runtime_foreach(self, **kwargs: Any) -> bool: ...

    def advance_runtime_bounded_loop(self, **kwargs: Any) -> Any: ...

    def finish_runtime_bounded_loop(self, **kwargs: Any) -> bool: ...

    def list_graph_revisions(self, run_id: str, **kwargs: Any) -> list[Any]: ...


class WorkerStorePort(Protocol):
    def register_runtime_worker(self, **kwargs: Any) -> None: ...

    def heartbeat_runtime_worker(
        self, worker_id: str, *, metadata: dict[str, Any] | None = None
    ) -> bool: ...

    def unregister_runtime_worker(self, worker_id: str) -> None: ...

    def wait_for_work(self, timeout: float) -> bool: ...

    def notify_work(self, run_id: str | None = None) -> None: ...

    def expire_stale_runtime_workers(self, **kwargs: Any) -> int: ...


class AgentCatalogStorePort(Protocol):
    def get_agent_revision(self, revision_id: str) -> AgentRevision | None: ...

    def get_agent_profile(self, agent_id: str | None = None) -> Any: ...

    def list_agent_profiles(self, *, active_only: bool = True) -> list[Any]: ...

    def get_agent_definition(self, agent_id: str) -> Any: ...

    def get_agent_team_revision(self, revision_id: str) -> Any: ...

    def get_published_agent_team(self, team_id: str) -> Any: ...

    def list_agent_team_revisions(self, team_id: str | None = None) -> list[Any]: ...

    def get_eval_run(self, eval_run_id: str) -> dict[str, Any] | None: ...

    def create_run_execution_snapshot(
        self,
        run_id: str,
        agent_id: str,
        *,
        revision_id: str | None = None,
    ) -> AgentExecutionSnapshot: ...

    def get_run_execution_snapshot(self, run_id: str) -> AgentExecutionSnapshot | None: ...

    def list_capability_definitions(self) -> list[dict[str, Any]]: ...

    def get_capability_definition(
        self, capability_id: str, version: str
    ) -> dict[str, Any] | None: ...

    def list_agent_skill_bindings(
        self, agent_revision_id: str
    ) -> list[dict[str, Any]]: ...

    def get_published_skill(
        self, skill_id: str, version: str
    ) -> dict[str, Any] | None: ...

    def list_skills(self, *, active_only: bool = False) -> list[dict[str, Any]]: ...


class ScenarioStorePort(Protocol):
    def get_run_scenario_state(
        self, run_id: str, *, expected_user_id: str | None = None
    ) -> Any: ...

    def get_scenario_version(self, scenario_id: str, version: str | int) -> Any: ...

    def list_scenario_versions(self, *, published_only: bool = False) -> list[Any]: ...

    def save_run_scenario_state(self, **kwargs: Any) -> Any: ...

    def create_input_request(self, **kwargs: Any) -> Any: ...


class ClarificationStorePort(Protocol):
    def get_run_scenario_state(
        self, run_id: str, *, expected_user_id: str | None = None
    ) -> Any: ...

    def get_scenario_version(self, scenario_id: str, version: str | int) -> Any: ...

    def save_run_scenario_state(self, **kwargs: Any) -> Any: ...

    def create_input_request(self, **kwargs: Any) -> Any: ...

    def get_input_request(self, input_request_id: str, **kwargs: Any) -> Any: ...

    def list_pending_input_requests(self, run_id: str, **kwargs: Any) -> list[Any]: ...

    def resolve_input_request(self, **kwargs: Any) -> bool: ...

    def resolve_dynamic_input_request(self, **kwargs: Any) -> bool: ...

    def notify_work(self, run_id: str | None = None) -> None: ...


class PlanningStorePort(Protocol):
    def list_runtime_turns(self, run_id: str) -> list[Any]: ...

    def record_loop_decision(self, **kwargs: Any) -> Any: ...

    def list_loop_decisions(self, run_id: str, **kwargs: Any) -> list[Any]: ...


class PlanConfirmationStorePort(Protocol):
    def create_plan_confirmation(self, **kwargs: Any) -> dict[str, Any]: ...

    def get_plan_confirmation(self, run_id: str) -> dict[str, Any] | None: ...

    def act_plan_confirmation(self, **kwargs: Any) -> dict[str, Any] | None: ...

    def queue_plan_confirmed_run(self, run_id: str) -> bool: ...

    def requeue_plan_regeneration(
        self, run_id: str, *, feedback: str
    ) -> dict[str, Any] | None: ...


class RuntimeLogStorePort(Protocol):
    def append_runtime_log(self, **kwargs: Any) -> Any: ...

    def list_runtime_logs(self, run_id: str, **kwargs: Any) -> list[Any]: ...


class TraceStorePort(Protocol):
    def append_request_trace_event(self, **kwargs: Any) -> Any: ...


class ExecutionStorePort(Protocol):
    """Durable journal, artifact and verification state used during execution."""

    def get_runtime_run(self, run_id: str, expected_user_id: str | None = None) -> Any: ...

    def create_runtime_turn(self, **kwargs: Any) -> tuple[Any, bool]: ...

    def record_runtime_turn_response(self, turn_id: str, **kwargs: Any) -> bool: ...

    def finish_runtime_turn(self, turn_id: str, **kwargs: Any) -> bool: ...

    def record_context_manifest(self, **kwargs: Any) -> Any: ...

    def get_context_manifest_for_turn(self, turn_id: str, **kwargs: Any) -> Any: ...

    def add_runtime_artifact(self, **kwargs: Any) -> None: ...

    def list_runtime_artifacts(self, run_id: str) -> list[dict[str, Any]]: ...

    def begin_verification(self, **kwargs: Any) -> Any: ...

    def complete_verification(self, verification_id: str, **kwargs: Any) -> Any: ...

    def list_verification_records(self, run_id: str, **kwargs: Any) -> list[Any]: ...

    def append_request_trace_event(self, **kwargs: Any) -> Any: ...


class ObservabilityStorePort(Protocol):
    def start_execution_span(self, **kwargs: Any) -> Any: ...

    def finish_execution_span(self, span_id: str, **kwargs: Any) -> bool: ...


class ReconciliationStorePort(Protocol):
    def get_action_reconciliation(self, action_id: str) -> Any: ...

    def list_action_intents(self, run_id: str) -> list[Any]: ...

    def get_action_observation(self, action_id: str) -> Any: ...


class TeamWorkspaceStorePort(Protocol):
    def list_team_workspace_entries(self, **kwargs: Any) -> list[Any]: ...


class ExperimentStorePort(Protocol):
    def record_experiment_assignment(self, **kwargs: Any) -> Any: ...

    def enforce_experiment_guardrails(self, experiment_id: str) -> dict[str, Any]: ...

    def select_experiment_variant(self, **kwargs: Any) -> dict[str, Any] | None: ...


class InvocationStorePort(Protocol):
    def list_capability_invocations(self, run_id: str, **kwargs: Any) -> list[Any]: ...


class WorkflowStorePort(Protocol):
    def create_user_workflow(self, **kwargs: Any) -> dict[str, Any]: ...

    def list_user_workflows(self, *, user_id: str) -> list[dict[str, Any]]: ...

    def get_user_workflow(self, workflow_id: str, **kwargs: Any) -> dict[str, Any] | None: ...

    def create_user_workflow_revision(self, **kwargs: Any) -> dict[str, Any] | None: ...

    def list_user_workflow_revisions(
        self, workflow_id: str, **kwargs: Any
    ) -> list[dict[str, Any]]: ...

    def publish_user_workflow(
        self, workflow_id: str, revision_id: str, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    def delete_user_workflow(self, workflow_id: str, *, user_id: str) -> bool: ...


class GraphPatchStorePort(Protocol):
    def get_graph_revision(self, revision_id: str, **kwargs: Any) -> Any: ...

    def propose_graph_patch(self, **kwargs: Any) -> tuple[Any, bool]: ...

    def apply_graph_patch(self, **kwargs: Any) -> tuple[Any, Any, bool]: ...

    def get_graph_patch_proposal(self, proposal_id: str, **kwargs: Any) -> Any: ...

    def reject_graph_patch_proposal(self, proposal_id: str, **kwargs: Any) -> Any: ...

    def claim_graph_patch_proposal(self, proposal_id: str, **kwargs: Any) -> Any: ...

    def finish_graph_patch_proposal(self, proposal_id: str, **kwargs: Any) -> Any: ...

    def list_graph_patches(self, run_id: str, **kwargs: Any) -> list[Any]: ...

    def list_graph_patch_proposals(self, run_id: str, **kwargs: Any) -> list[Any]: ...


class AppDependencyStorePort(Protocol):
    def get_plugin_release(self, plugin_id: str, version: str) -> dict[str, Any] | None: ...

    def is_plugin_execution_enabled(self, plugin_id: str) -> bool: ...

    def get_remote_connection(self, connection_id: str) -> dict[str, Any] | None: ...


class MaintenanceStorePort(Protocol):
    def reconcile_configuration_rollouts(self) -> Any: ...

    def expire_due_approval_requests(self, **kwargs: Any) -> list[Any]: ...

    def expire_plan_confirmations(self, **kwargs: Any) -> list[Any]: ...

    def purge_old_runtime_data(self, **kwargs: Any) -> dict[str, int]: ...


@dataclass(frozen=True, slots=True)
class RuntimeStores:
    """Explicit capability views over one transactional storage backend."""

    runs: RunStorePort
    tasks: TaskStorePort
    events: EventStorePort
    graphs: GraphStorePort
    workers: WorkerStorePort
    catalog: AgentCatalogStorePort
    logs: RuntimeLogStorePort
    traces: TraceStorePort
    scenarios: ScenarioStorePort
    maintenance: MaintenanceStorePort
    execution: ExecutionStorePort
    observability: ObservabilityStorePort
    reconciliations: ReconciliationStorePort
    experiments: ExperimentStorePort
    team_workspace: TeamWorkspaceStorePort
    planning: PlanningStorePort
    plan_confirmations: PlanConfirmationStorePort
    clarifications: ClarificationStorePort
    invocations: InvocationStorePort
    workflows: WorkflowStorePort
    graph_patches: GraphPatchStorePort
    app_dependencies: AppDependencyStorePort

    @classmethod
    def from_backend(cls, backend: object) -> RuntimeStores:
        """Expose narrow views without splitting the backend transaction boundary."""
        explicit_views = getattr(type(backend), "runtime_stores", None)
        if callable(explicit_views):
            return cast(RuntimeStores, explicit_views(backend))
        return cls(
            runs=cast(RunStorePort, backend),
            tasks=cast(TaskStorePort, backend),
            events=cast(EventStorePort, backend),
            graphs=cast(GraphStorePort, backend),
            workers=cast(WorkerStorePort, backend),
            catalog=cast(AgentCatalogStorePort, backend),
            logs=cast(RuntimeLogStorePort, backend),
            traces=cast(TraceStorePort, backend),
            scenarios=cast(ScenarioStorePort, backend),
            maintenance=cast(MaintenanceStorePort, backend),
            execution=cast(ExecutionStorePort, backend),
            observability=cast(ObservabilityStorePort, backend),
            reconciliations=cast(ReconciliationStorePort, backend),
            experiments=cast(ExperimentStorePort, backend),
            team_workspace=cast(TeamWorkspaceStorePort, backend),
            planning=cast(PlanningStorePort, backend),
            plan_confirmations=cast(PlanConfirmationStorePort, backend),
            clarifications=cast(ClarificationStorePort, backend),
            invocations=cast(InvocationStorePort, backend),
            workflows=cast(WorkflowStorePort, backend),
            graph_patches=cast(GraphPatchStorePort, backend),
            app_dependencies=cast(AppDependencyStorePort, backend),
        )
