"""Storage contract for the durable, distributed agent runtime."""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from porthouse.contracts.events import AgentEvent
from porthouse.domain.agents import (
    AgentDefinition,
    AgentExecutionSnapshot,
    AgentProfile,
    AgentRevision,
)
from porthouse.domain.capabilities import CapabilityDefinition, CapabilityInvocation
from porthouse.domain.scenarios import ScenarioVersion
from porthouse.storage.agent_team_store import AgentTeamStore
from porthouse.storage.app_pack_store import AppPackStore
from porthouse.storage.approval_records import ApprovalRequestRecord
from porthouse.storage.context_records import ContextManifestRecord
from porthouse.storage.decision_records import LoopDecisionRecord
from porthouse.storage.device_host_store import DeviceHostStore
from porthouse.storage.execution_records import (
    ActionIntentRecord,
    ActionObservationRecord,
    RuntimeTurnRecord,
)
from porthouse.storage.external_configuration_store import ExternalConfigurationStore
from porthouse.storage.graph_event_records import GraphEventWaitRecord
from porthouse.storage.graph_patch_records import GraphPatchRecord
from porthouse.storage.graph_revision_records import GraphRevisionRecord
from porthouse.storage.input_asset_records import InputAssetRecord
from porthouse.storage.observability_records import (
    ExecutionSpanRecord,
    ModelInvocationRecord,
    ReasoningSegmentRecord,
    ReplayRunRecord,
    TraceBlobRecord,
)
from porthouse.storage.platform_records import (
    CapabilityInvocationRecord,
    ConfigurationEventRecord,
    ConfigurationRolloutRecord,
    InputRequestRecord,
    PlatformAdminRecord,
    RunFeedbackRecord,
    RunScenarioStateRecord,
)
from porthouse.storage.reconciliation_records import OperationReconciliationRecord
from porthouse.storage.verification_records import VerificationRecord

DESTRUCTIVE_MIGRATE_PHRASE = "DROP_ALL_TABLES"


def destructive_migrate_enabled() -> bool:
    """Whether a development schema reset is explicitly allowed.

    Development-only escape hatch: the environment variable must equal the
    exact phrase ``DROP_ALL_TABLES``; truthy values such as ``1`` no longer
    qualify, so a casually exported flag cannot wipe production data.
    """
    return (
        os.environ.get("PORTHOUSE_DESTRUCTIVE_MIGRATE", "").strip() == DESTRUCTIVE_MIGRATE_PHRASE
    )


@dataclass(slots=True)
class RuntimeRunRecord:
    run_id: str
    user_id: str
    session_id: str
    agent_id: str
    kind: str
    status: str
    prompt: str
    options: dict[str, Any]
    result: dict[str, Any] | None
    error: dict[str, Any] | None
    idempotency_key: str | None
    created_at: str
    started_at: str | None
    finished_at: str | None
    updated_at: str
    lease_owner: str | None
    lease_expires_at: str | None
    lease_version: int = 0
    root_run_id: str | None = None
    parent_run_id: str | None = None
    parent_task_id: str | None = None
    current_phase: str | None = None
    status_summary: str | None = None
    status_reason: str | None = None
    next_action: str | None = None
    waiting_on: str | None = None
    active_turn_id: str | None = None
    active_span_count: int = 0
    completed_task_count: int = 0
    total_task_count: int = 0
    last_event_sequence: int = 0
    last_progress_at: str | None = None
    cancel_requested_at: str | None = None
    cancel_reason: str | None = None
    graph_revision_id: str | None = None


@dataclass(slots=True)
class RuntimeTaskRecord:
    task_id: str
    run_id: str
    agent_id: str
    parent_task_id: str | None
    name: str
    status: str
    payload: dict[str, Any]
    result: dict[str, Any] | None
    error: dict[str, Any] | None
    priority: int
    attempt: int
    max_attempts: int
    available_at: str
    lease_owner: str | None
    lease_expires_at: str | None
    created_at: str
    started_at: str | None
    finished_at: str | None
    updated_at: str
    lease_version: int = 0


@dataclass(slots=True)
class RuntimeLogRecord:
    sequence: int
    run_id: str
    task_id: str | None
    worker_id: str | None
    level: str
    stage: str
    message: str
    data: dict[str, Any]
    created_at: str


@dataclass(slots=True)
class RequestTraceEventRecord:
    """One immutable milestone in an end-to-end request timeline."""

    sequence: int
    event_id: str
    tracker_id: str
    request_id: str
    parent_request_id: str | None
    user_id: str | None
    run_id: str | None
    transport: str
    direction: str
    operation: str
    stage: str
    status: str | None
    data: dict[str, Any]
    created_at: str


@runtime_checkable
class RuntimeStore(AgentTeamStore, AppPackStore, DeviceHostStore, ExternalConfigurationStore, Protocol):
    """Backend-neutral runtime contract used by FastAPI and workers.

    Methods are deliberately synchronous: database drivers remain isolated from
    the event loop with ``asyncio.to_thread`` in the runtime.
    """

    backend_name: str

    def upsert_platform_admin(self, **kwargs: Any) -> PlatformAdminRecord: ...

    def get_platform_admin(self, user_id: str) -> PlatformAdminRecord | None: ...

    def list_platform_admins(self) -> list[PlatformAdminRecord]: ...

    def delete_platform_admin(self, user_id: str, *, actor_id: str) -> bool: ...

    def list_platform_admin_events(self, *, limit: int = 200) -> list[dict[str, Any]]: ...

    def create_api_access_token(self, **kwargs: Any) -> tuple[dict[str, Any], str]: ...

    def authenticate_api_access_token(self, token: str) -> dict[str, Any] | None: ...

    def list_api_access_tokens(self, *, limit: int = 500) -> list[dict[str, Any]]: ...

    def revoke_api_access_token(self, token_id: str, *, actor_id: str) -> bool: ...

    def set_admin_password(self, **kwargs: Any) -> bool: ...

    def get_admin_login_credential(self, user_id: str) -> dict[str, Any] | None: ...

    def record_admin_login_failure(self, user_id: str, **kwargs: Any) -> dict[str, Any] | None: ...

    def record_admin_login_success(self, user_id: str) -> None: ...

    def create_admin_auth_challenge(self, user_id: str, **kwargs: Any) -> tuple[str, str]: ...

    def get_admin_auth_challenge(self, token: str) -> dict[str, Any] | None: ...

    def record_admin_auth_challenge_failure(self, token: str, **kwargs: Any) -> None: ...

    def consume_admin_auth_challenge(self, token: str) -> bool: ...

    def create_admin_auth_session(
        self, user_id: str, **kwargs: Any
    ) -> tuple[dict[str, Any], str]: ...

    def authenticate_admin_session(self, token: str) -> dict[str, Any] | None: ...

    def revoke_admin_auth_session(self, session_id: str, *, actor_id: str) -> bool: ...

    def set_admin_totp_pending(self, user_id: str, **kwargs: Any) -> str | None: ...

    def activate_admin_totp(self, user_id: str, **kwargs: Any) -> bool: ...

    def accept_admin_totp_counter(self, user_id: str, counter: int) -> bool: ...

    def consume_admin_recovery_code(self, user_id: str, code_hash: str) -> bool: ...

    def disable_admin_totp(self, user_id: str, *, actor_id: str) -> bool: ...

    def get_admin_auth_status(self, user_id: str) -> dict[str, Any] | None: ...

    def save_agent_revision(self, definition: AgentDefinition, revision: AgentRevision) -> None: ...

    def publish_agent_revision(
        self, agent_id: str, revision_id: str, *, actor_id: str = "system"
    ) -> AgentProfile: ...

    def get_agent_revision(self, revision_id: str) -> AgentRevision | None: ...

    def get_agent_definition(self, agent_id: str) -> AgentDefinition | None: ...

    def list_agent_definitions(self, *, active_only: bool = False) -> list[AgentDefinition]: ...

    def list_agent_revisions(self, agent_id: str) -> list[AgentRevision]: ...

    def get_agent_profile(self, agent_id: str | None = None) -> AgentProfile | None: ...

    def list_agent_profiles(self, *, active_only: bool = True) -> list[AgentProfile]: ...

    def list_published_agent_profiles(self) -> list[AgentProfile]: ...

    def create_run_execution_snapshot(
        self, run_id: str, agent_id: str
    ) -> AgentExecutionSnapshot: ...

    def get_run_execution_snapshot(self, run_id: str) -> AgentExecutionSnapshot | None: ...

    def bind_agent_skill(self, **kwargs: Any) -> None: ...

    def list_agent_skill_bindings(self, agent_revision_id: str) -> list[dict[str, Any]]: ...

    def unbind_agent_skill(self, **kwargs: Any) -> bool: ...

    def save_skill_draft(self, value: dict[str, Any], *, actor_id: str) -> dict[str, Any]: ...

    def validate_skill_version(
        self, skill_id: str, version: str, *, actor_id: str | None = None
    ) -> dict[str, Any]: ...

    def stage_skill_version(self, skill_id: str, version: str, **kwargs: Any) -> str: ...

    def list_skills(self, *, active_only: bool = False) -> list[dict[str, Any]]: ...

    def get_skill(self, skill_id: str) -> dict[str, Any] | None: ...

    def list_skill_versions(self, skill_id: str) -> list[dict[str, Any]]: ...

    def get_skill_version(self, skill_id: str, version: str) -> dict[str, Any] | None: ...

    def get_published_skill(
        self, skill_id: str, version: str | None = None
    ) -> dict[str, Any] | None: ...

    def set_skill_status(self, skill_id: str, *, status: str, actor_id: str) -> bool: ...

    def list_memory_documents(self, **kwargs: Any) -> list[dict[str, Any]]: ...

    def summarize_memory_documents(self, **kwargs: Any) -> dict[str, Any]: ...

    def get_memory_document(self, **kwargs: Any) -> dict[str, Any] | None: ...

    def list_memory_candidates(self, **kwargs: Any) -> list[Any]: ...

    def create_event_trigger(self, **kwargs: Any) -> dict[str, Any]: ...

    def list_event_triggers(self, *, user_id: str) -> list[dict[str, Any]]: ...

    def get_event_trigger(
        self, trigger_id: str, *, expected_user_id: str | None = None
    ) -> dict[str, Any] | None: ...

    def update_event_trigger(self, **kwargs: Any) -> dict[str, Any] | None: ...

    def rotate_event_trigger_secret(
        self, trigger_id: str, *, user_id: str, secret_hash: str
    ) -> dict[str, Any] | None: ...

    def delete_event_trigger(self, trigger_id: str, *, user_id: str) -> bool: ...

    def begin_event_trigger_delivery(self, **kwargs: Any) -> dict[str, Any]: ...

    def complete_event_trigger_delivery(
        self, delivery_id: str, *, run_id: str
    ) -> dict[str, Any] | None: ...

    def fail_event_trigger_delivery(
        self, delivery_id: str, *, error: str
    ) -> dict[str, Any] | None: ...

    def list_event_trigger_deliveries(self, **kwargs: Any) -> list[dict[str, Any]]: ...

    def list_configuration_events(self, *, limit: int = 200) -> list[ConfigurationEventRecord]: ...

    def list_configuration_rollouts(
        self, *, limit: int = 100
    ) -> list[ConfigurationRolloutRecord]: ...

    def list_configuration_rollout_targets(self, rollout_id: str) -> list[dict[str, Any]]: ...

    def get_configuration_rollout(self, rollout_id: str) -> ConfigurationRolloutRecord | None: ...

    def list_pending_configuration_revisions(
        self, worker_id: str
    ) -> list[dict[str, str]]: ...

    def list_pending_agent_revisions(self, worker_id: str) -> list[dict[str, str]]: ...

    def acknowledge_agent_revision(self, **kwargs: Any) -> bool: ...

    def acknowledge_configuration_revision(self, **kwargs: Any) -> bool: ...

    def approve_configuration_rollout(self, rollout_id: str, *, actor_id: str) -> bool: ...

    def cancel_configuration_rollout(self, rollout_id: str, *, actor_id: str) -> bool: ...

    def retry_configuration_rollout(self, rollout_id: str, *, actor_id: str) -> bool: ...

    def rollback_configuration_rollout(self, rollout_id: str, *, actor_id: str) -> bool: ...

    def reconcile_configuration_rollouts(self) -> int: ...

    def stage_capability_release(
        self, definition: CapabilityDefinition, **kwargs: Any
    ) -> None: ...

    def get_capability_release_definition(
        self, capability_id: str, version: str
    ) -> dict[str, Any] | None: ...

    def get_capability_definition(
        self, capability_id: str, version: str | None = None
    ) -> dict[str, Any] | None: ...

    def list_capability_definitions(self) -> list[dict[str, Any]]: ...

    def get_capability_runtime_settings(self, capability_id: str) -> dict[str, Any]: ...

    def save_capability_runtime_settings(
        self, capability_id: str, *, enabled: bool, configuration: dict[str, Any],
        actor_id: str, capability_version: str | None = None
    ) -> dict[str, Any]: ...

    def upsert_plugin_release(self, manifest: dict[str, Any]) -> None: ...

    def stage_plugin_release(
        self, plugin_id: str, version: str, **kwargs: Any
    ) -> str: ...

    def sync_plugin_components(
        self, plugin_id: str, plugin_version: str, components: list[dict[str, Any]], **kwargs: Any
    ) -> None: ...

    def list_plugin_releases(self) -> list[dict[str, Any]]: ...

    def get_plugin_release(
        self, plugin_id: str, version: str | None = None
    ) -> dict[str, Any] | None: ...

    def get_active_plugin_release(self, plugin_id: str) -> dict[str, Any] | None: ...

    def list_plugin_components(
        self, plugin_id: str, plugin_version: str | None = None
    ) -> list[dict[str, Any]]: ...

    def list_plugin_workers(self, plugin_id: str) -> list[dict[str, Any]]: ...

    def get_plugin_metrics(self, plugin_id: str, *, hours: int = 24) -> dict[str, Any]: ...

    def list_plugin_recent_invocations(
        self, plugin_id: str, *, limit: int = 100
    ) -> list[dict[str, Any]]: ...

    def create_capability_invocation(
        self, invocation: CapabilityInvocation
    ) -> tuple[CapabilityInvocationRecord, bool]: ...

    def get_capability_invocation(
        self, invocation_id: str
    ) -> CapabilityInvocationRecord | None: ...

    def start_capability_invocation(self, invocation_id: str, *, worker_id: str) -> bool: ...

    def finish_capability_invocation(self, invocation_id: str, **kwargs: Any) -> bool: ...

    def list_capability_invocations(
        self, run_id: str, *, expected_user_id: str | None = None
    ) -> list[CapabilityInvocationRecord]: ...

    def save_scenario_version(
        self, scenario: ScenarioVersion, *, status: str = "draft", actor_id: str = "system"
    ) -> None: ...

    def publish_scenario(
        self, scenario_id: str, version: int, *, actor_id: str = "system"
    ) -> None: ...

    def stage_scenario_release(
        self, scenario_id: str, version: int, **kwargs: Any
    ) -> None: ...

    def get_scenario_version(
        self, scenario_id: str, version: int | None = None
    ) -> ScenarioVersion | None: ...

    def list_scenario_versions(self, *, published_only: bool = True) -> list[ScenarioVersion]: ...

    def create_user_workflow(self, **values: Any) -> dict[str, Any]: ...

    def list_user_workflows(self, *, user_id: str) -> list[dict[str, Any]]: ...

    def get_user_workflow(
        self, workflow_id: str, *, expected_user_id: str
    ) -> dict[str, Any] | None: ...

    def create_user_workflow_revision(self, **values: Any) -> dict[str, Any] | None: ...

    def list_user_workflow_revisions(
        self, workflow_id: str, *, user_id: str
    ) -> list[dict[str, Any]]: ...

    def publish_user_workflow(
        self, workflow_id: str, revision_id: str, *, user_id: str
    ) -> dict[str, Any] | None: ...

    def delete_user_workflow(self, workflow_id: str, *, user_id: str) -> bool: ...

    def save_run_scenario_state(self, **kwargs: Any) -> RunScenarioStateRecord: ...

    def get_run_scenario_state(
        self, run_id: str, *, expected_user_id: str
    ) -> RunScenarioStateRecord | None: ...

    def create_input_request(self, **kwargs: Any) -> InputRequestRecord: ...

    def get_input_request(
        self, input_request_id: str, *, expected_user_id: str
    ) -> InputRequestRecord | None: ...

    def list_pending_input_requests(
        self, run_id: str, *, expected_user_id: str
    ) -> list[InputRequestRecord]: ...

    def list_pending_user_input_requests(
        self, *, user_id: str, limit: int = 100
    ) -> list[dict[str, Any]]: ...

    def resolve_input_request(self, **kwargs: Any) -> bool: ...

    def resolve_dynamic_input_request(self, **kwargs: Any) -> bool: ...

    def create_runtime_run(self, **kwargs: Any) -> tuple[RuntimeRunRecord, bool]: ...

    def create_input_asset(self, **kwargs: Any) -> tuple[InputAssetRecord, bool]: ...

    def get_input_asset(
        self, asset_id: str, *, expected_user_id: str
    ) -> InputAssetRecord | None: ...

    def delete_input_asset(
        self, asset_id: str, *, expected_user_id: str, actor_id: str
    ) -> InputAssetRecord | None: ...

    def get_bound_input_asset(
        self, asset_id: str, *, run_id: str, expected_user_id: str
    ) -> InputAssetRecord | None: ...

    def list_run_input_assets(
        self, run_id: str, *, expected_user_id: str
    ) -> list[InputAssetRecord]: ...

    def audit_input_asset_read(
        self, *, asset_id: str, run_id: str, user_id: str
    ) -> None: ...

    def materialize_runtime_graph(self, **kwargs: Any) -> RuntimeRunRecord: ...

    def list_graph_revisions(
        self, run_id: str, *, expected_user_id: str
    ) -> list[GraphRevisionRecord]: ...

    def get_graph_revision(
        self, revision_id: str, *, expected_user_id: str
    ) -> GraphRevisionRecord | None: ...

    def apply_graph_patch(
        self, **kwargs: Any
    ) -> tuple[GraphPatchRecord, RuntimeRunRecord, bool]: ...

    def suspend_graph_task_for_subrun(self, **kwargs: Any) -> bool: ...

    def list_graph_patches(
        self, run_id: str, *, expected_user_id: str
    ) -> list[GraphPatchRecord]: ...

    def check_api_rate_limit(self, rate_key: str, **kwargs: Any) -> bool: ...

    def get_runtime_run(
        self, run_id: str, expected_user_id: str | None = None
    ) -> RuntimeRunRecord | None: ...

    def claim_runtime_run(self, run_id: str, **kwargs: Any) -> RuntimeRunRecord | None: ...

    def heartbeat_runtime_run(self, run_id: str, **kwargs: Any) -> bool: ...

    def list_runtime_runs(self, **kwargs: Any) -> list[RuntimeRunRecord]: ...

    def count_runtime_runs(self, **kwargs: Any) -> int: ...

    def delete_runtime_session(self, **kwargs: Any) -> int:
        """Delete terminal runs owned by one user/session/agent."""
        ...

    def list_incomplete_runtime_runs(self, limit: int = 500) -> list[RuntimeRunRecord]: ...

    async def purge_old_runtime_data(self, older_than_ms: int) -> dict[str, int]:
        """Delete runtime events/logs/trace events older than the epoch-ms cutoff.

        Returns the number of rows deleted per table.
        """
        ...

    def update_runtime_run(self, run_id: str, **kwargs: Any) -> bool: ...

    def request_runtime_cancel(self, run_id: str, **kwargs: Any) -> dict[str, Any] | None: ...

    def finish_runtime_run_bundle(
        self, run_id: str, **kwargs: Any
    ) -> tuple[list[AgentEvent], AgentEvent] | None: ...

    def reset_runtime_run(self, run_id: str) -> bool: ...

    def reset_runtime_graph(self, run_id: str) -> bool: ...

    def append_runtime_event(self, event: AgentEvent) -> AgentEvent: ...

    def list_runtime_events(self, run_id: str, **kwargs: Any) -> list[AgentEvent]: ...

    def create_runtime_turn(self, **kwargs: Any) -> tuple[RuntimeTurnRecord, bool]: ...

    def get_runtime_turn(self, turn_id: str) -> RuntimeTurnRecord | None: ...

    def list_runtime_turns(self, run_id: str) -> list[RuntimeTurnRecord]: ...

    def record_runtime_turn_response(self, turn_id: str, **kwargs: Any) -> bool: ...

    def finish_runtime_turn(self, turn_id: str, **kwargs: Any) -> bool: ...

    def create_action_intent(self, **kwargs: Any) -> tuple[ActionIntentRecord, bool]: ...

    def get_action_intent(self, action_id: str) -> ActionIntentRecord | None: ...

    def claim_action_intent(self, action_id: str, *, worker_id: str) -> bool: ...

    def record_action_observation(self, **kwargs: Any) -> tuple[ActionObservationRecord, bool]: ...

    def get_action_observation(self, action_id: str) -> ActionObservationRecord | None: ...

    def list_action_intents(self, run_id: str) -> list[ActionIntentRecord]: ...

    def record_context_manifest(self, **kwargs: Any) -> ContextManifestRecord | None: ...

    def get_context_manifest_for_turn(
        self, turn_id: str, **kwargs: Any
    ) -> ContextManifestRecord | None: ...

    def list_context_manifests(self, run_id: str, **kwargs: Any) -> list[ContextManifestRecord]: ...

    def record_loop_decision(self, **kwargs: Any) -> LoopDecisionRecord | None: ...

    def list_loop_decisions(self, run_id: str, **kwargs: Any) -> list[LoopDecisionRecord]: ...

    def create_approval_request(self, **kwargs: Any) -> tuple[ApprovalRequestRecord, bool]: ...

    def get_approval_request(
        self, approval_id: str, *, expected_user_id: str | None = None
    ) -> ApprovalRequestRecord | None: ...

    def get_action_approval(self, action_id: str) -> ApprovalRequestRecord | None: ...

    def list_run_approval_requests(
        self, run_id: str, *, expected_user_id: str
    ) -> list[ApprovalRequestRecord]: ...

    def list_pending_user_approval_requests(
        self, *, user_id: str, limit: int = 100
    ) -> list[dict[str, Any]]: ...

    def suspend_run_for_approval(self, **kwargs: Any) -> bool: ...

    def resolve_approval_request(self, **kwargs: Any) -> ApprovalRequestRecord | None: ...

    def claim_approved_action(self, action_id: str, *, worker_id: str) -> bool: ...

    def expire_due_approval_requests(self, *, limit: int = 500) -> list[ApprovalRequestRecord]: ...

    def ensure_operation_reconciliation(
        self, **kwargs: Any
    ) -> tuple[OperationReconciliationRecord, bool]: ...

    def get_operation_reconciliation(
        self, reconciliation_id: str, *, expected_user_id: str | None = None
    ) -> OperationReconciliationRecord | None: ...

    def get_action_reconciliation(self, action_id: str) -> OperationReconciliationRecord | None: ...

    def list_run_operation_reconciliations(
        self, run_id: str, *, expected_user_id: str
    ) -> list[OperationReconciliationRecord]: ...

    def claim_operation_reconciliation(
        self, reconciliation_id: str, **kwargs: Any
    ) -> OperationReconciliationRecord | None: ...

    def persist_operation_reconciliation_observation(self, reconciliation_id: str, **kwargs: Any) -> Any: ...
    def list_operation_reconciliation_events(self, reconciliation_id: str, **kwargs: Any) -> list[Any]: ...

    def defer_operation_reconciliation(self, reconciliation_id: str, **kwargs: Any) -> bool: ...

    def suspend_run_for_reconciliation(self, **kwargs: Any) -> bool: ...

    def complete_operation_reconciliation(
        self, reconciliation_id: str, **kwargs: Any
    ) -> OperationReconciliationRecord | None: ...

    def retry_operation_reconciliation(
        self, reconciliation_id: str, **kwargs: Any
    ) -> OperationReconciliationRecord | None: ...

    def create_artifact_upload_grant(self, **kwargs: Any) -> Any: ...
    def get_artifact_upload_grant_by_token(self, grant_id: str, **kwargs: Any) -> Any: ...
    def commit_artifact_upload(self, grant_id: str, **kwargs: Any) -> Any: ...
    def claim_artifact_upload(self, **kwargs: Any) -> Any: ...
    def materialize_artifact_upload(self, grant_id: str, **kwargs: Any) -> bool: ...
    def fail_artifact_upload(self, grant_id: str, **kwargs: Any) -> bool: ...

    def create_runtime_task(self, **kwargs: Any) -> RuntimeTaskRecord: ...

    def suspend_graph_task_for_approval(self, **kwargs: Any) -> bool: ...

    def suspend_graph_task_for_explicit_approval(
        self, **kwargs: Any
    ) -> ApprovalRequestRecord | None: ...

    def suspend_graph_task_for_reconciliation(self, **kwargs: Any) -> bool: ...

    def refresh_runtime_graph_wait_state(self, run_id: str) -> None: ...

    def get_runtime_task(self, task_id: str) -> RuntimeTaskRecord | None: ...

    def list_runtime_tasks(self, **kwargs: Any) -> list[RuntimeTaskRecord]: ...

    def get_runtime_task_dependencies(self, task_id: str) -> list[str]: ...

    def update_runtime_task(self, task_id: str, **kwargs: Any) -> bool: ...

    def complete_runtime_branch(self, **kwargs: Any) -> tuple[bool, list[str]]: ...

    def expand_runtime_foreach(self, **kwargs: Any) -> dict[str, Any]: ...

    def complete_runtime_foreach(self, **kwargs: Any) -> dict[str, Any] | None: ...
    def advance_runtime_bounded_loop(self, **kwargs: Any) -> dict[str, Any]: ...
    def finish_runtime_bounded_loop(self, **kwargs: Any) -> bool: ...
    def trigger_runtime_saga(self, run_id: str) -> dict[str, Any] | None: ...
    def reconcile_runtime_saga(self, run_id: str) -> dict[str, Any] | None: ...
    def get_runtime_saga(self, run_id: str) -> dict[str, Any] | None: ...

    def suspend_graph_task_for_event(self, **kwargs: Any) -> GraphEventWaitRecord | None: ...

    def list_graph_event_waits(
        self, run_id: str, *, expected_user_id: str
    ) -> list[GraphEventWaitRecord]: ...

    def get_graph_event_wait(
        self, wait_id: str, *, expected_user_id: str | None = None
    ) -> GraphEventWaitRecord | None: ...

    def issue_graph_event_token(
        self, wait_id: str, *, expected_user_id: str, actor_id: str | None = None
    ) -> tuple[GraphEventWaitRecord, str] | None: ...

    def receive_graph_event(self, wait_id: str, **kwargs: Any) -> dict[str, Any]: ...

    def expire_due_graph_event_waits(self, **kwargs: Any) -> list[GraphEventWaitRecord]: ...

    def claim_runtime_task(self, **kwargs: Any) -> RuntimeTaskRecord | None: ...

    def heartbeat_runtime_task(self, task_id: str, **kwargs: Any) -> bool: ...

    def cancel_runtime_tasks(self, run_id: str) -> int: ...

    def reset_runtime_tasks(self, run_id: str) -> int: ...

    def reconcile_runtime_graph(self, run_id: str) -> dict[str, int]: ...

    def start_runtime_graph(self, run_id: str) -> bool: ...

    def add_runtime_artifact(self, **kwargs: Any) -> None: ...

    def list_runtime_artifacts(self, run_id: str) -> list[dict[str, Any]]: ...

    def begin_verification(self, **kwargs: Any) -> VerificationRecord | None: ...

    def complete_verification(
        self, verification_id: str, **kwargs: Any
    ) -> VerificationRecord | None: ...

    def list_verification_records(self, run_id: str, **kwargs: Any) -> list[VerificationRecord]: ...

    def append_runtime_log(self, **kwargs: Any) -> RuntimeLogRecord: ...

    def list_runtime_logs(self, run_id: str, **kwargs: Any) -> list[RuntimeLogRecord]: ...

    def get_session_state(self, storage_key: str) -> dict[str, Any] | None: ...

    def save_session_state(
        self,
        storage_key: str,
        *,
        session_key: str,
        namespace: str,
        state: dict[str, Any],
    ) -> None: ...

    def delete_session_state(self, storage_key: str) -> bool: ...

    def list_session_states(self, *, namespace: str, limit: int = 1000) -> list[dict[str, Any]]: ...

    def append_request_trace_event(self, **kwargs: Any) -> RequestTraceEventRecord:
        """Persist one append-only request/response/error milestone."""
        ...

    def list_request_trace_events(
        self, tracker_id: str, **kwargs: Any
    ) -> list[RequestTraceEventRecord]:
        """Return a tracker timeline in creation order."""
        ...

    def expire_stale_runtime_workers(self, *, stale_after_seconds: int = 120) -> int:
        """Mark abandoned worker registrations offline using their heartbeat lease."""
        ...

    def list_runtime_workers(self, *, limit: int = 500) -> list[dict[str, Any]]: ...

    def get_platform_overview(self) -> dict[str, Any]: ...

    def get_user_model_usage(self, user_id: str) -> dict[str, Any]: ...

    def put_trace_blob(
        self, *, run_id: str, kind: str, content: Any, **kwargs: Any
    ) -> TraceBlobRecord: ...

    def get_trace_blob(self, blob_id: str) -> TraceBlobRecord | None: ...

    def list_trace_blobs(self, run_id: str) -> list[TraceBlobRecord]: ...

    def start_execution_span(self, **kwargs: Any) -> ExecutionSpanRecord: ...

    def mark_execution_span_first_token(self, span_id: str) -> bool: ...

    def finish_execution_span(self, span_id: str, **kwargs: Any) -> bool: ...

    def list_execution_spans(self, run_id: str) -> list[ExecutionSpanRecord]: ...

    def create_model_invocation(self, **kwargs: Any) -> ModelInvocationRecord: ...

    def mark_model_invocation_first_token(self, invocation_id: str) -> bool: ...

    def finish_model_invocation(self, invocation_id: str, **kwargs: Any) -> bool: ...

    def list_model_invocations(self, run_id: str) -> list[ModelInvocationRecord]: ...

    def append_reasoning_segment(self, **kwargs: Any) -> ReasoningSegmentRecord: ...

    def list_reasoning_segments(
        self, run_id: str, **kwargs: Any
    ) -> list[ReasoningSegmentRecord]: ...

    def create_replay_run(self, **kwargs: Any) -> ReplayRunRecord: ...

    def update_replay_run(self, replay_id: str, **kwargs: Any) -> bool: ...

    def get_replay_run(self, replay_id: str) -> ReplayRunRecord | None: ...

    def list_replay_runs(self, source_run_id: str) -> list[ReplayRunRecord]: ...

    def create_run_feedback(self, **kwargs: Any) -> RunFeedbackRecord: ...

    def list_run_feedback(self, run_id: str, **kwargs: Any) -> list[RunFeedbackRecord]: ...

    def get_model_response_cache(self, cache_key: str) -> dict[str, Any] | None: ...

    def put_model_response_cache(self, cache_key: str, **kwargs: Any) -> None: ...

    def notify_work(self, run_id: str | None = None) -> None: ...

    def wait_for_work(self, timeout: float) -> bool: ...

    def healthcheck(self) -> dict[str, Any]: ...

    def runtime_metrics(self) -> dict[str, Any]: ...

    def operational_metrics(self) -> dict[str, Any]: ...

    def enqueue_eval_execution(self, eval_run_id: str, **kwargs: Any) -> dict[str, Any]: ...

    def get_eval_execution_job(self, eval_run_id: str) -> dict[str, Any] | None: ...

    def claim_eval_execution_job(self, **kwargs: Any) -> dict[str, Any] | None: ...

    def heartbeat_eval_execution_job(self, eval_run_id: str, **kwargs: Any) -> bool: ...

    def complete_eval_execution_job(self, eval_run_id: str, **kwargs: Any) -> bool: ...

    def fail_eval_execution_job(self, eval_run_id: str, **kwargs: Any) -> bool: ...

    def upsert_eval_schedule_policy(self, **kwargs: Any) -> dict[str, Any]: ...

    def list_eval_schedule_policies(self) -> list[dict[str, Any]]: ...

    def reconcile_due_eval_schedules(self, *, limit: int = 20) -> int: ...

    def check_embedding_rate_limit(self, profile_revision_id: str, **kwargs: Any) -> bool: ...

    def close(self) -> None: ...
